[package]
name = "post-install"
version = "0.1.0"
authors = ["Sergey Kuznetsov <sergey.gh@fastmail.net>"]
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0.104", features = ["derive"] }
