[package]
name = "arch-postinstall"
version = "0.1.0"
authors = ["Sergey Kuznetsov <cmt@phnx47.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
