name: Build Rust Project

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: ./cargo.sh build --release

    - uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: target/release/arch-post-install
